# shared-volume.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watched-pvc
  namespace: rm-embeddings
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rm-embeddings-pvc
  namespace: rm-embeddings
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
